version: "3.5"

services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: khaochae-game-web
    ports:
      - "3002:3000"
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
